### ISSUE TITLE
TLS/SSL Support

### ISSUE THREAD

**Issue by danielbjornadal** [felixgborrego/docker-ui-chrome-app#43]
Cant find anything on SSL support?
Would be great to be able to add key and certificate when connecting to the docker API :)

**Comment by felixgborrego** [comment]
Closing this issue, 
Not sure if I understood, but Docker Remote API uses by default TLS/SSL, actually you need to install a valid client certificate in order to connect with the Docker Remote API 

https://github.com/felixgborrego/docker-ui-chrome-app/wiki/Mac-OS-X
https://github.com/felixgborrego/docker-ui-chrome-app/wiki/windows

**Comment by danielbjornadal** [comment]
Many do not use docker machine. You can connect directly yo the docker API (https://docs.docker.com/engine/reference/api/docker_remote_api/) and controll it from there. But to be able to do this securely, you must add the option to add certificate. Just try to connect directly to the docker engine at port 2375.
https://docs.docker.com/engine/quickstart/
